- name: Agregando repositorio externo ppa:nginx/stable
  apt_repository: repo='ppa:nginx/stable' state=present

- name: Actualizando la cahe de apt
  apt: update_cache=yes

- name: Instalando nginx-full
  apt: name=nginx-full state=present

- name: Utilizando nginx con el usuario vagrant
  lineinfile: dest=/etc/nginx/nginx.conf regexp='^user' line='user vagrant;'

- name: Pasando la configuración de sitio para nginx
  template: src=server.j2 dest=/etc/nginx/sites-enabled/{{ configs.dominio }}.conf
  notify: reiniciar nginx

- name: Eliminando el sitio predefinido nginx
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reiniciar nginx
