- name: Instalando php{{ php.version }}-fpm
  apt: name=php{{ php.version }}-fpm state=present

- name: Modificaciones en php date.timezone = America/Mexico_City;
  lineinfile: dest=/etc/php/{{ php.version }}/fpm/php.ini regexp='^;date.timezone =' line='date.timezone = America/Mexico_City;'

- name: Modificaciones en php para Drupal cgi.fix_pathinfo = 0;
  lineinfile: dest=/etc/php/{{ php.version }}/fpm/php.ini regexp='^;cgi.fix_pathinfo' line='cgi.fix_pathinfo = 0;'

- name: Modificaciones en php para Drupal upload_max_filesize = {{ php.max_up_size }};
  lineinfile: dest=/etc/php/{{ php.version }}/fpm/php.ini regexp='^upload_max_filesize' line='upload_max_filesize = {{ php.max_up_size }};'

- name: Modificaciones en php para Drupal post_max_size = {{ php.max_post_size }};
  lineinfile: dest=/etc/php/{{ php.version }}/fpm/php.ini regexp='^upload_max_filesize' line='upload_max_filesize = {{ php.max_post_size }};'

- name: Modificaciones en php para Drupal max_execution_time = {{ php.max_execution_time }};
  lineinfile: dest=/etc/php/{{ php.version }}/fpm/php.ini regexp='^max_execution_time' line='max_execution_time = {{ php.max_execution_time }};'

- name: Eliminando la configuración predeterminada
  file: path=/etc/php/{{ php.version }}/fpm/pool.d/www.conf state=absent

- name: reescribiendo la configuración fpm pools
  template: src=pool-template.j2 dest=/etc/php/{{ php.version }}/fpm/pool.d/{{ item.name }}.conf
  with_items: '{{ fpm }}'
  notify: reiniciando php-fpm
