- name: Agregando el apt de mysql 8
  apt: deb=http://dev.mysql.com/get/mysql-apt-config_0.8.12-1_all.deb

- name: Actualizando la cahe de apt
  apt: update_cache=yes

- name: Instalando mysql-server
  apt: name=mysql-server state=present

- name: Instalando mysql-client
  apt: name=mysql-client state=present

- name: Instalando MySQL-python
  apt: name=python-mysqldb state=present
