- name: Configuración necesaria en /etc/security/limits.conf
  template: src=solr-template.j2 dest=/etc/security/limits.conf

- name: Descargando solr-{{ solr.version }}
  get_url:
    url: https://www-us.apache.org/dist/lucene/solr/{{ solr.version }}/solr-{{ solr.version }}.tgz
    dest: /opt/solr-{{ solr.version }}.tgz

- name: Descomprimiendo solr-{{ solr.version }}
  command: tar xzf solr-{{ solr.version }}.tgz solr-{{ solr.version }}/bin/install_solr_service.sh --strip-components=2
  args:
    chdir: /opt

- name: Instalando y levantando servicio solr-{{ solr.version }}
  command: bash ./install_solr_service.sh solr-{{ solr.version }}.tgz
  args:
    chdir: /opt
